# Vault's Kubernetes auth binds the role of vaultAgent.auth.role to this service account and its
# namespace.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "proxy.serviceAccountName" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
automountServiceAccountToken: false
