# Vault's Kubernetes auth binds the role of vault.auth.role to this service account and its
# namespace.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aisa.serviceAccountName" . }}
  labels:
    {{- include "aisa.labels" . | nindent 4 }}
automountServiceAccountToken: false
